#! /bin/bash

count=10 

if [ $count -eq 10 ]
 then
    echo "la condition est verifie"
fi

cou=49

if (( $cou > 30 )); then
	echo "this is also true"
fi

stri="mor"

if [[ $stri == "mor" ]]; then
	echo merci 
fi

alph=a

if [[ $alph = "b" ]]; then
	echo "verified"
elif [[ $alph < b ]]; then
		echo "true"
else
echo "false"		
fi