#!/bin/bash

nb1=$1
inv=0
if [[ $# -lt 1 || $# -gt 1 ]]; 
then
	echo "erreur de syntaxe : $0 +<nombre> "
else
	while [[ $nb1 -gt 0 ]]; do
		last=$(($nb1%10))
		inv=$((($inv*10) + $last))	
		nb1=$(($nb1/10))
	done
	echo $inv
fi	

